pipeline:
  build:
    image: golang:1.11.1-alpine
    commands:
      - pwd
      - export GOPATH=/go
      - export CGO_ENABLED=0
      - export GOPROXY=https://goproxy.io
      - pwd
      - ls
      - go build -v
      - ls
      - pwd