pipeline:
  build:
    image: golang:1.11.1-alpine
    commands:
      - pwd
      - export GOPATH=/go
      - export CGO_ENABLED=0
      - export GOPROXY=https://goproxy.io
      - pwd
      - ls
      - go build -v
      - ls
      - pwd
  docker_latest:
    image: docker
    repo: gin-web
    dockerfile: Dockerfile
    when:
      branch: master
      event: [push, pull_request]
    docker_tag:
      image: docker
      repo: gin-web
      dockerfile: Dockerfile
      default_tags: true
      when:
        branch: master
        event: [tag]